config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "movies#index"

  resources :movies, only: [:index, :show]
  resources :lists, only: [:index, :show, :new, :create]
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
     @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to lists_path
    else
      render :new
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(
      :comment, :movie_id
    )
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end

    def edit
      @list = List.edit

    end

    def update
      @list.update(list_params)
      redirect ti list_path
    end

    def destroy
      @list.def destroy
      redirect to lists_path
    end
  end

  private

  def list_params
    params.require(:list).permit(
      :name
    )
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

  # <% @list.movies.each do |movie| %>
  #   <%= f.label :to, movie.title %>
  #     <%= f.check_box :to, {}, movie.title %>
  #   <% end %>
  # <% end %>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.input :movie_id, collection: Movie.all, prompt: 'Select a movie', input_html: { class: 'select2' } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>Lists</h1>
    <ul class="list-group">
      <% @lists.each do |list| %>
        <li class="list-group-item"><%= link_to list.name, list_path(list) %></li>
      <% end %>
    </ul>
  <%= link_to  "Create a new list", new_list_path %>
  <br>
  <%= link_to  "Back to Movies", movies_path %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New list</h1>
  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
          <h3>Add a movie to your <%= @list.name %> list</h3>
          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
            <%= f.association :movie, prompt: 'Select a movie', input_html: { class: 'select2' } %>
            <%= f.submit class: 'btn btn-flat' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to  "Back to Lists", lists_path %>
</div>

app/views/lists/show.html.erb
<h1>List name</h1>
<h2><%= @list.name%></h2>
<ul class="list-group">
  <% @list.movies.each do |movie| %>
    <li <%= movie.title %></li>
  <% end %>
</ul>
  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <div class="card" style="width: 18rem;">
          <%= image_tag movie.poster_url, alt: movie.title, class: 'movie-img rounded-top' %>
          <div class="card-body">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <div>
              <i class="fas fa-quote-left mr-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              <small class="text-right flex-shrink-0"><%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
    <% end %>
  </div>
<%= link_to  "Back to Lists", lists_path %>
<p><%= link_to "Create a bookmark", new_bookmark_path(@list) %></p>

app/views/movies/index.html.erb
<div class="container">
  <h1>Movie index</h1>
  <ul class="list-group">
    <% @movies.each do |movie| %>
      <li class="list-group-item"><%= link_to movie.title, movie_path(movie) %></li>
    <% end %>
  </ul>
<%= link_to  "View Lists", lists_path %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <h1><%= @movie.title %></h1>
  <p><%= @movie.overview %></p>
  <p><%= @movie.rating %>🍋</p>
  <div class="container">
    <p><img src=<%= @movie.poster_url %> style="width:200px;" alt=<% @movie.title + "poster" %> ></p>
  </div>
  <%= link_to  "Back to Movies", movies_path %>
</div>